### ISSUE TITLE
Bug Report: Epiphany crashes always i want to start it

### ISSUE THREAD

**Issue by Dantilo50** [Jorge-SunSpirit/Doki-Doki-Takeover#23] opened 2023-03-14 00:12 UTC
I even reset all my data to check if i do something wrong in the history but nothing, the crash said this C:\HaxeToolkit\haxe\std/cpp/_std/sys/io/Process.hx (line 97)
CoolUtil.hx (line 75)
PlayState.hx (line 651)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Process creation failure : tasklist
Please report this error to the GitHub page: https://github.com/Jorge-SunSpirit/Doki-Doki-Takeover

> Crash Handler written by: sqirra-rng
Can someone help me with this?

**Comment by ActualMandM** [comment] 2023-03-14 00:42
Duplicate of #22, will be fixed in v3.0.2.

**Closed by ActualMandM** 2023-03-14 00:42 UTC
Labels: bug

**Comment by Dantilo50** [comment] 2023-03-14 00:43
> Duplicate of #22, will be fixed in v3.0.2.

Thanks
